spring:
  application:
    name: kafka-crud
  datasource:
    url: jdbc:h2:mem:db_kafka
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    baseline-on-migrate: true
    locations: "classpath:db/migration"
  h2:
    console:
      enabled: true
      path: /h2-console

kafka-config:
  bootstrap-servers: localhost:9092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:9092

server:
  port: 8282
